set -g mouse on

set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

bind -n S-Left  previous-window
bind -n S-Right next-window

bind r source-file ~/.tmux.conf \;

set -g status-style "bg=#8A2BE2,fg=white"


set -g status-left-length 40
set -g status-left "#[fg=black,bg=#E0B0FF,bold]  #S #[bg=#8A2BE2,fg=white] "

# --- Plugins ---
# set -g @plugin 'tmux-plugins/tpm'
# set -g @plugin 'tmux-plugins/tmux-battery'
# set -g @plugin 'tmux-plugins/tmux-cpu'

# run '~/.tmux/plugins/tpm/tpm'
